{% set name = "fundamentals" %}
{% set version = "2.6.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: e2a08098a6960d9784bc1cfa1cbf6ffd096761a71ea116ade993b9f4d600a4a0

build:
  number: 0
  noarch: python
  entry_points:
    - mysqlSucker=fundamentals.mysql.directory_script_runner:main
    - yaml2db=fundamentals.mysql.yaml_to_database:main
    - sqlite2mysql=fundamentals.mysql.sqlite2mysql:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - docopt
    - future
    - psutil
    - python >=3.8
    - python-dateutil
    - pyyaml
    - requests
    - python-daemon

test:
  imports:
    - fundamentals

about:
  home: https://github.com/thespacedoctor/fundamentals
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  summary: Some fundamental tools required by most self-respecting python-packages bundled in one place. Very opinionated project setup tools including logging, plain-text settings files and database connections.
  doc_url: https://fundamentals.readthedocs.io
  dev_url: https://github.com/thespacedoctor/fundamentals

extra:
  recipe-maintainers:
    - thespacedoctor
