{% set name = "fundamentals" %}
{% set version = "2.4.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: b9b277f46297b98606b885b2f047ebe20a361a4724b21da48e55c8b5cea4f26c

build:
  number: 0
  noarch: python
  entry_points:
    - mysqlSucker=fundamentals.mysql.directory_script_runner:main
    - yaml2db=fundamentals.mysql.yaml_to_database:main
    - sqlite2mysql=fundamentals.mysql.sqlite2mysql:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - coloredlogs
    - docopt
    - future
    - psutil
    - python >=3.8
    - python-dateutil
    - pyyaml
    - requests
    - python-daemon

test:
  imports:
    - fundamentals
    - fundamentals.commonutils
    - fundamentals.download
    - fundamentals.files
    - fundamentals.mysql
    - fundamentals.nose2_plugins
    - fundamentals.renderer
    - fundamentals.stats
  commands:
    - mysqlSucker --help
    - yaml2db --help
    - sqlite2mysql --help

about:
  home: https://github.com/thespacedoctor/fundamentals
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  summary: Some fundamental tools required by most self-respecting python-packages bundled in one place. Very opinionated project setup tools including logging, plain-text settings files and database connections.
  doc_url: https://fundamentals.readthedocs.io
  dev_url: https://github.com/thespacedoctor/fundamentals

extra:
  recipe-maintainers:
    - thespacedoctor
